http:
  port: 8081
  adminPort: 8081

ddslConfig:
  zookeeperHosts: localhost:2181
  serviceId:
    environment: test
    name: ddsl-example-other
    version: 1.0

serviceName: other-service

otherService:
    environment: test
    name: ddsl-example
    version: 1.0
