server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

ddslConfig:
  zookeeperHosts: localhost:2181
  #serviceUrl: http://public.example.com:port/
  serviceId:
    environment: test
    name: ddsl-example
    version: 1.0

serviceName: main-service

otherService:
    environment: test
    name: ddsl-example-other
    version: 1.0
