http:
  port: 8080
  adminPort: 8080

ddslConfig:
  zookeeperHosts: localhost:2181
  #serviceUrl: http://public.example.com:port/
  serviceId:
    environment: test
    name: ddsl-example
    version: 1.0

serviceName: main-service

otherService:
    environment: test
    name: ddsl-example-other
    version: 1.0
